### PR TITLE
[iris] get list beneficiary banks

### PR DESCRIPTION
**Pull request by mychaelgo**
this is my first work on iris, i create simple wrapper to get list beneficiary banks

If this PR approved, i continue to write another iris wrapper
Please take a look @rizdaprasetya , please let me know what do you thought

### CODE REVIEW

**Comment by rizdaprasetya** [comment]
Hi @mychaelgo thanks for contributing!

So far looks good and consistent enough with current implementation.

https://github.com/veritrans/go-midtrans/pull/26/files#diff-fe6b69ef4717d5933c0042b80f5f3246R24
Would be better if the func name is `GetListBeneficiaryBank`

Other than that, looks fine
👍

**Comment by mychaelgo** [comment]
@rizdaprasetya ok noted, func name already replaced

**Comment by rizdaprasetya** [comment]
Great, thanks, let me test and merge when appropriate

**Comment by rizdaprasetya** [comment]
Tested, looks good. will merge.

**Pull request merged**
