### PR TITLE
Return error when order id has been utilized

### PR DESCRIPTION
**Pull request by mychaelgo**
**Context**
Return clear error message 

**Reference**
https://github.com/veritrans/go-midtrans/blob/master/iris.go#L142

**Sample code**
```go
	var snapGateway midtrans.SnapGateway
	snapGateway = midtrans.SnapGateway{
		Client: midclient,
	}

	snapReq := midtrans.SnapReq{
		TransactionDetails: midtrans.TransactionDetails{
			OrderID:  "go-client-1",
			GrossAmt: 100000,
		},
		CustomerDetail: &midtrans.CustDetail{
			FName: "Mychael",
			Email: "email@example.com",
			Phone: "+628134567890",
		},
		CustomField1: "test go client",
	}
	res, err := snapGateway.GetToken(&snapReq)
	fmt.Println("res ==> %v", res)
	fmt.Println("err ==> %v", err)
```

Here i want to propose returning error message in `err` instead of `nil` if `error_messages` JSON field is not null

### CODE REVIEW

**Comment by mychaelgo** [comment]
@rizdaprasetya please review

**Comment by rizdaprasetya** [comment]
Make great sense, nice 👍  
Thanks will merge.

**Comment by rizdaprasetya** [comment]
This will also take care of returning err on any other error message, not just duplicated order_id 👌

**Comment by mychaelgo** [comment]
@rizdaprasetya yes of course

**Pull request merged**
