### PR TITLE
Improve Go Report Card and add LICENSE

### PR DESCRIPTION
**Pull request by haritsfahreza**
Hi @rizdaprasetya and Midtrans team,

Based on issue #11 , I'd like to create pull request to make this library more awesome! 😄 

You can check the Go Report Card difference between my fork repo and this repo before this PR approved in here : 
https://goreportcard.com/report/github.com/haritsfahreza/go-midtrans (fork)
https://goreportcard.com/report/github.com/veritrans/go-midtrans (master)

Also I add Apache 2.0 LICENSE file, regarding into the issue #10 

Please take a look 🙏

### CODE REVIEW

**Comment by rizdaprasetya** [comment]
Hi @haritsfahreza , 
This is great improvement, let me review once I have the chance and get back to you (or merge the PR. approx by today).
Thanks for keep actively contributing! 😃

**Comment by rizdaprasetya** [comment]
👍  Sure, you can add Apache 2.0 license here as well, that's what we gonna use for integration libraries.

**Comment by haritsfahreza** [comment]
Done @rizdaprasetya , please take a look 🙏

**Comment by rizdaprasetya** [comment]
All looks good, great catch on style and best practice improvement 👍 
I'll merge it now.
Thanks for the contribution.

**Comment by haritsfahreza** [comment]
Thankyou! @rizdaprasetya

**Pull request merged**
