### PR TITLE
Change envtype value and make the unit test works

### PR DESCRIPTION
**Pull request by haritsfahreza**
Hi Midtrans team! Based on Midtrans Core API docs https://api-docs.midtrans.com, I'd like to contribute to this library by changing the envtype URL from veritrans.co.id to midtrans.com. Please take a look 😄

### CODE REVIEW

**Comment by haritsfahreza** [comment]
Hi @rizdaprasetya thanks for responding my PR 😄 

I was concerned also about the indentations. But, according to https://golang.org/doc/effective_go.html#formatting, they said that they use `tabs` as default indentations. I also use `gofmt` as my default formatter. So WDYT?

**Comment by rizdaprasetya** [comment]
Oh right, ok you have good reason for that. I agree. I guess it won't be serious issue about the style consistency. The more important thing is as long as community can easily contribute, we're good.

Also about this new commit
https://github.com/veritrans/go-midtrans/pull/9/commits/535198e574f743d64b6124dcca681a61928cb802
You added new Core API example, would be nice to change the file name from `snap_index.html` to `core_api_index.html`

thanks.

**Comment by haritsfahreza** [comment]
@rizdaprasetya , according to previous example, `index.html` is the implementation example of Core API. So IMO I just rename the `index.html` to `core_api_index.html` and change the router on `main.go`. Please take a look 🙏

**Comment by rizdaprasetya** [comment]
@haritsfahreza 
Oh sorry I misunderstood because inside the `snap_index.html` you were [mentioning Core API](https://github.com/veritrans/go-midtrans/pull/9/commits/843ccfdcf4fa2d07655490422f035aa402af7269#diff-1987b040bc4e9f8e16ad2d4a4fc2ff2cL26)
So I think you need to change '[via Core API](https://github.com/veritrans/go-midtrans/pull/9/commits/843ccfdcf4fa2d07655490422f035aa402af7269#diff-1987b040bc4e9f8e16ad2d4a4fc2ff2cL26)' to `via Snap`

other than that, everything looks good.

thanks.

**Comment by rizdaprasetya** [comment]
@haritsfahreza Oh my bad sorry, yes you were right, it's a link title. I thought it was the checkout button label. Then you are correct.

Good ideas, feel free if you want to add it.
Let me know if  this PR ready to be merged.

**Comment by haritsfahreza** [comment]
Done @rizdaprasetya ! It's ready to be merged 😄

**Comment by rizdaprasetya** [comment]
Cool 👍 thanks for your contribution and cooperation 😃 
We'll merge it now

**Pull request merged**
